pull_request_rules:
  - name: Automatic merge of Snyk dependency upgrades
    conditions:
      - "author=snyk-bot"
      - "-conflict"
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
      - "status-success=security/snyk (lukemnet)"
    actions:
      merge:
        method: squash
        strict: true
  - name: Automatic merge of Dependabot dependency upgrades
    conditions:
      - "author=dependabot[bot]"
      - "-conflict"
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
      - "status-success=security/snyk (lukemnet)"
    actions:
      merge:
        method: squash
        strict: truepull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
